### ISSUE TITLE
Index name value for OpenSearch data sources isn't being transmitted

### ISSUE THREAD

**Issue by AlKapkone** [grafana/opensearch-datasource#25]
I've used the latest version of the Grafana OpenSearch datasource and when I configure grafana using the official helm chart it's doesn't transmit an index name.
grafana-opensearch-datasource **v1.1.2** (latest)
Grafana version - **v8.4.2**
```
      - name: Jaeger Beta OpenSearch
        version: 1
        editable: true
        database: beta-jaeger-span-*
        type: grafana-opensearch-datasource
        access: proxy
        url: https://opensearch.logs.example.com
        basicAuth: true
        basicAuthUser: grafana
        basicAuthPassword: supersecretpassword
        jsonData:
          maxConcurrentShardRequests: 256
          timeField: startTimeMillis
          timeInterval: 15s
          version: '1.1.0'
          flavor: 'opensearch'
```
I also tried various combinations and variants:
```
database: '[metrics-]YYYY.MM.DD'
database: '[metrics-*]'
```

If we check this datasource in Grafana - OpenSearch details -> Index name is empty.
<img width="888" alt="Знімок екрана 2022-03-22 о 18 54 58" src="https://user-images.githubusercontent.com/24461114/159533618-c05d39e6-88dd-43ac-b0f0-f9ce4bee8e35.png">

What should I do to set this value?
