### ISSUE TITLE
opensearch-datasource fail to start with permission denied error if use S3 as persistent volume 

### ISSUE THREAD

**Issue by FedorAredakov** [grafana/opensearch-datasource#301]
We deploy Grafana with kube-prometheus-stack helm chart into Kubernetes cluster and want to use s3 as a persistent volume to store Grafana settings.
```resource "kubernetes_persistent_volume" "pv-prometheus-s3-grafana" {
  metadata {
    name      = "monitoring-prometheus-s3-grafana"
}
  spec {
    capacity = {
    storage = "150Gi"
}
  access_modes = ["ReadWriteMany"]
  storage_class_name =  "csi-s3"
  persistent_volume_source {
    csi {
      driver = "ru.yandex.s3.csi"
      volume_handle = "prometheus-data-metrics/prometheus/grafana"
      controller_publish_secret_ref {
        namespace = "kube-system"
        name      = "csi-s3-secret"
      }
      node_publish_secret_ref {
        name      = "csi-s3-secret"
        namespace = "kube-system"
      }
      node_stage_secret_ref {
        name      = "csi-s3-secret"
        namespace = "kube-system"
      }
      volume_attributes = {
        capacity  = "150Gi"
        mounter   = "geesefs"
        options   = "--memory-limit=1000 --dir-mode=0777 --file-mode=0666 --uid=1001"
      }
    }
   }
  }
}
```
we use this helm values:
```
## PVC
  persistence:
    type: pvc
    enabled: true
    storageClassName: "csi-s3"
    volumeName: monitoring-prometheus-s3-grafana
    accessModes:
      - ReadWriteMany
    size: 150Gi
    finalizers:
      - kubernetes.io/pvc-protection
    extraPvcLabels: { }
```
After applying this settings Grafana fail to start with `chown: /var/lib/grafana: Operation not supported` error.
We found out that error disappear if enable initChownData settings:
```
 initChownData:
    enabled: true
```
Everything fine, except using opensearch-datasource plugin.
It can't start getting data with the error `fork/exec /var/lib/grafana/plugins/grafana-opensearch-datasource/gpx_opensearch-datasource_linux_amd64: permission denied` because of the initChownData setting.

So if 
```
 initChownData:
    enabled: true
``` 
then Grafana works fine with S3 storage, but the plugin doesn't work.
If
```
initChownData:
    enabled: false
```
then Grafana doesn’t work.

If we use normal K8s Persistent Volume everything works fine, but it's very important for us to use S3 as storage.

**Environment**:
- Grafana version: v.9.3.1
- Plugin version: 2.13.1
