### ISSUE TITLE
Setting basicAuthPassword in provisioned datasource.yaml doesn't work

### ISSUE THREAD

**Issue by janbaer** [grafana/opensearch-datasource#327]
**What happened**:

I'm trying to configure a datasource for opensource from the provisioning folder in the same way, I did before with the Elasticsearch provider. In the `datasources.yaml` I have the following configuration

```yaml
- name: BU-ELK
  type: grafana-opensearch-datasource
  access: proxy
  url: "https:/....."
  basicAuth: true
  basicAuthUser: "grafana"
  basicAuthPassword: "mypassword"
  jsonData:
    database: "[bu-k8s-logs-]YYYY.MM.DD"
    interval: Daily
    timeField: "@timestamp"
    version: "1.0.0"
    flavor: "opensearch"
```

The datasource with all fields will be read correctly except `basicAuthPassword`. This field will be shown empty in the configuration editor and that's why the connection test fails. Since the connection was created automatically, I can not change the password. When I configure a datasource manually with a password, the connection works fine.

**What you expected to happen**: The predefined password should be used and the connection should work.

**Anything else we need to know?**:

I also tried to move the basicAuthPassword to the jsonData but with the same result.

**Environment**:
- Grafana version: 9.5.15
- OpenSearch version: 2.11.1
- Plugin version: 2.14.3
