### ISSUE TITLE
Index missing when provisioning Opensearch datasource

### ISSUE THREAD

**Issue by KerimDjiho** [grafana/opensearch-datasource#34]
Hi, pretty much as the title says. When we tested out the plugin manually it worked fine, but when provisioned the index is completely missing.
```
- name: Datasource-name-placeholder-1
  type: grafana-opensearch-datasource
  access: proxy
  url: https://vpc-prod-company-opensearch.eu-central-1.es.amazonaws.com
  database: 'index-1-*'
  jsonData:
    keepCookies: []
	maxConcurrentShardRequests: 256
	timeField: cts
	
- name: Datasource-name-placeholder-2
  type: grafana-opensearch-datasource
  access: proxy
  url: https://vpc-prod-company-opensearch.eu-central-1.es.amazonaws.com
  database: 'index-2-*'
  jsonData:
    keepCookies: []
    maxConcurrentShardRequests: 256
    timeField: cts
```
Any and all help is appreciated.
